### ISSUE TITLE
Prismarine temples cause worldgen lag.

### ISSUE THREAD

**Issue by Neodark7** [ganymedes01/Gany-s-Surface#26]
![capture](https://cloud.githubusercontent.com/assets/7981869/6137418/05ac437c-b179-11e4-90e2-e924611b9ce0.PNG)

**Comment by Neodark7** [comment]
huu now it's 30k µs :/

**Comment by ganymedes01** [comment]
wow that doesn't seem ideal lol
Could you try disabling the prismarine temple generation and see if that solves it?
It's the only thing I can think of that would be causing that much lag. The 1.8 stones are generated exactly the same way as they are in 1.8 so I highly doubt it's their fault.

Something else that could be causing the problem is the dynamic snow (not really world gen, but it's handled in the world tick event), try disabling that and see if it helps.

Other than those, I can't think of anything else causing that much lag...
Please let me know anything you find. And thank you for the report.

**Comment by Neodark7** [comment]
i'll do that right now ! thank you :)

**Comment by Neodark7** [comment]
like that I:prismarineTempleChance=0 ? instead of 800

**Comment by ganymedes01** [comment]
The latter :3

**Comment by Neodark7** [comment]
i have disabled both x) btw what is the thaumcraft integration ? i have many problems when crafting things in the arcane worktable. probably related ?

**Comment by Neodark7** [comment]
YAY no more gany surface line in handlers <3 i love you x) my server is still laggy with other mods handlers and things but this is solved thank you :D

**Comment by Neodark7** [comment]
at least for the moment :3

**Comment by ganymedes01** [comment]
The thaumcraft integration is just aspects added to a few items. I doubt it would be interfering with crafting in the arcane worktable.

And I'm glad you found the issue, I'll have to go find out how to solve it XD

**Comment by Neodark7** [comment]
okay :) thank you again i love your mod and i was afraid to need to remove it ^^ happy to help :)
