### ISSUE TITLE
(Aesthetic) More stuff from different wood and other suggestions

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Surface#31]
Want to request some more stuff from different wood types (which will have own texture based on wood type). Like Oak Chest, Spruce Chest etc.
List of stuff:
- [x] Vanilla Trapdoors (Not *disguised* versions)
- [x] Sticks (They are registered as *stickWood*, shouldn't be hard?)
- [ ] Boats (Why not?)
- [x] Buttons
- [x] Ladders
- [x] Signs
- [x] Pressure Plates
- [ ] Different wooden tools? Low priority.
- [x] Bookshelves

Console Edition Items:
- [x] Donkey Spawn Egg
- [x] Mule Spawn Egg

Most of requested stuff are not registered in Ore Dictionary, so mods may wont accept them in crafting. Is it hard to make very simple converter block which will convert things from different wood to vanilla item. I.e Acacia Crafting Table -> Vanilla Crafting Table. I think this can solve the compatibility problem.

Some 1.8 features:
1. Heads should have cracking animation. Both vanilla and Gany's Surface. Not sure if it possible. Also, any Gany's Surface head when placed displayed as *Blaze Head* on one second, possible to fix?
2. Signs, beacons, should have cracking animation too.
3. Double Chests and beds should have *connected* cracking animation, is it possible?
4. Fence gates, dead bushes, saplings should catch fire.
5. Melons, Ladders should be mined faster with an axe and Packed ice faster with a pickaxe.

If you are implement these features (or some of them) this mod will become even more nicer :smile:

**Comment by ganymedes01** [comment]
I like the idea of having single wood items for each type of wood. While buttons, pressure plates, signs  and etc would be easy (since they just use the wood texture) the others would be a bit harder to do due to my limited texturing skills (no point adding a bunch of trapdoors if they all look dreadful lol). I'll see if anyone is willing to help on twitter :3

1- Cracking animations for heads: tried but it's impossible without core modding. Showing a blaze head for one frame: Not worth the effort, still a lot better than the vanilla player heads that actually freeze the server =P

2- Same as the heads. Would require core modding.

3- Same as 2. The single chest cracking animation is only possible due to a dirty hack I managed to pull off XD

4- They don't? lol

5- Should be pretty easy to do :3

**Comment by Adaptivity** [comment]
Thanks for answer. Hope you'll find someone who can make some textures for you. That would be great.
About cracking animation: Maybe you can add it as config option which will be disabled by default and people who want it can enable it? Of course if you can code this hack and it'll not take too much your time.
4. Yeah, 1.8 only feature :D

**Comment by ganymedes01** [comment]
I won't be doing torches. They don't have a ore dictionary name by default and are used in many recipes throughout many mods. Not to mention they are tiny and most people don't even use them after the early game (replacing them by other mod's fancy lights)

**Comment by Adaptivity** [comment]
Nice work. I seems forgot about bookshelves, what do you think? Also what do you think about ExtrabiomesXL support? It already has doors, fences and gates. I don't know how hard it will be supporting it, I guess it just a lot of texture work? Issue updated feel free to edit :D

**Comment by ganymedes01** [comment]
Support for other mod's woods is, in no way, viable. Far too many textures to be done, and would also end up generating a huge amount of items that aren't all that necessary.

**Comment by ganymedes01** [comment]
Tools would just be annoying tbh
And boats are broken enough as they are, I don't think I'll venture into adding more of them XD

So that's all of it done now :D
