### ISSUE TITLE
Can't craft torches from modded sticks

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Surface#53]
Title says it all. I can't craft torches using new sticks.

**Comment by Adaptivity** [comment]
Hope you didn't miss this @ganymedes01 :smile:

**Comment by ganymedes01** [comment]
Whoops, I didn't miss it, just forgot to reply :3

You have a mod that's messing with the torch recipe. Forge automatically replaces all of the vanilla recipes with OreDictionary ones (so torches will use stickWood instead of Items.stick as their ingredient), which means the only way it would not be working is if a mod is removing the Forge recipe and adding their own that uses only Items.stick

**Comment by Adaptivity** [comment]
Ok, thanks for info. I found the mod which broke the recipe. It's [IguanaTweaks changes the number of torches you will get](https://github.com/Parker8283/IguanaTweaks/blob/449f3e507b0e39faa0ec44d227d5316347f80336/src/main/java/iguanaman/iguanatweaks/IguanaTweaks.java#L93-L94). I'll inform @Parker8283

**Comment by ganymedes01** [comment]
Sent him a PR: https://github.com/Parker8283/IguanaTweaks/pull/50

**Comment by Adaptivity** [comment]
Thanks :3
