### ISSUE TITLE
[Config Feature] - [Quite Urgent]; Add a Config Option to disable the "special" vanilla wood sticks

### ISSUE THREAD

**Issue by Lanse505** [ganymedes01/Gany-s-Surface#57]
Please add a Config option to disable the special sticks crafted from each Vanilla wood. 
They don't work in all recipes and thus makes crafting certain things very hard. 

Anyway, Hope this won't be too big of a annoyance and be cleared out of the way in a quick little hotfix.

**Comment by ganymedes01** [comment]
1- Any mod that adds recipes that don't work with my sticks is in the wrong. They are registered in the OreDictionary which has been in place for centuries. All mods should be using it by now.

2- The sticks are in solely because they are used in the ladders recipes. If you absolutely dispise the sticks, disable ladders and they'll go away.

3- You should be able to turn any of my sticks into the vanilla ones by placing them alone in a crafting table (can't remember if I've added that feature before the last release, so I might be wrong here)

Hope this clears it all out :)

**Comment by Lanse505** [comment]
-Hugs Gany-senpai- :) didn't mean to come off as angry, Didnt know they got disabled by disabling the Ladders. Only worked from the info I had which was "Whenever i craft normal sticks i get Gany's sticks and they don't work with mod X. Y. Z. 

Thanks for the quick response and have a good one :) <3

**Comment by ganymedes01** [comment]
Sorry if I came off as angry as well, I was just trying to be as clear as possible :3
Have a good day :)
