### ISSUE TITLE
Can't access vanilla crafting table

### ISSUE THREAD

**Issue by Adaptivity** [ganymedes01/Gany-s-Surface#59]
This happens to me since the first version with "no recipe conflict mode". I just can't access vanilla crafting table. I thought that No recipe conflict mod messed up it because I forgot to remove it when updated Gany's Surface. But no, still can't access it. Disabling "No Recipe Conflict for Crafting Tables" fixes the problem. I can provide modpack if needed.
Mods installed: http://i.imgur.com/pexi5ug.jpg
Forge 1481
Config: In config I've disabled 1.8 stones and doors since those added by another mod.

**Comment by ganymedes01** [comment]
Very strange... no idea what could be going one there.
Do any of those mods you're using mess with the crafting table in any way?

**Comment by Adaptivity** [comment]
As far as I know, no. The only mod which interacted with vanilla crafting table is No more recipe conflict but it's got removed. I've [uploaded a .zip archive](https://www.dropbox.com/s/zemdykapkffdk5y/totest.zip?dl=0) with mods and config folders. Maybe you'll find a culprit.

**Comment by ganymedes01** [comment]
Thank you, downloaded it.
I'll test it later :3

**Comment by Dulciphi** [comment]
Hello again. I'm not sure if this can help you in any way with this issue, but I've just crashed when accessing the vanilla crafting table myself. If this seems like another issue, let me know please? 
http://pastebin.com/cyV40kN5

Thanks

**Comment by ganymedes01** [comment]
It's caused by CustomNPCs, it modifies the crafying recipes list every game tick (no idea why...) which causes the crash. Unfirtunatelly there's nothing I can do about it. The only way to avoid the crash is by turning the feature off or removing CustomNPCs

**Comment by Dulciphi** [comment]
Ahhh thank you for that info. In that case.. does your NoMoreRecipeConflict setting work in Tinker's workbenches? The NoMoreRecipeConflict mod doesn't and I'm just trying to weigh up pros and cons until (hopefully) the customNPCs issue is fixed

**Comment by ganymedes01** [comment]
It doesn't, but I heard boni is re-writing TiCon's crafting tables, maybe you should ask him to support it (he'd have to implement it himself, but my mod is open source, so he'd be more than welcome to see how I did it)

As for the issue with CustomNPCs being resolved... I can't fix it, they are the ones that will have to do it.
Although I tried to reproduce the issue on my end and was unable to. So it might even be a third mod causing CustomNPCs to break Gany's Surface...
I re-wrote some parts of the system recently (so that the buttons only show up if there is actually a conflict. Makes the GUI cleaner), so who knows.. maybe the issue fixed itself =P

**Comment by Adaptivity** [comment]
Seems to be fixed.
